# -*- coding: utf-8 -*-
"""Full workflow with panda-gym.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LvEgZdtZYaJ_upHR0K1nlkHaZV1rd10w
"""

!pip install wandb tensorboard

!pip install panda_gym==2.0.0

!pip install stable_baselines3



import gym
import wandb
import panda_gym
from stable_baselines3 import A2C
from stable_baselines3.common.vec_env import DummyVecEnv, SubprocVecEnv


wandb.init(project='panda-reach-a2c')

# Definition de l'environement
env_id = 'PandaReachJointsDense-v2'
env = gym.make(env_id)




# Defintion de l'agent A2C 
model = A2C('MultiInputPolicy', env, verbose=1)
model.learn(total_timesteps=500000)

# Sauvegarde du modele
wandb.save('model.zip')
model.save('model.zip')